Objetivo 4
jesusmarzor/Peluqueria pull request #33
Opened 2021-11-06 21:15 UTC by jesusmarzor

2021-11-07 10:12 UTC, jesusmarzor commented
Listo para revisión @JJ

2021-11-09 13:15 UTC, JJ requested changes
Los issues no son tareas, son problemas a resolver. Los mensajes de commit explican cómo se resuelve. Por favor, revisa la lista de comprobación de este objetivo.

2021-11-09 13:15 UTC, JJ commented on docs/Objetivo-4/TEST.md
> +## Librería
No has justificado la biblioteca de aserciones.

2021-11-09 13:15 UTC, JJ commented on src/App.js
> +                day['appointments'][hour] = false;
¿Qué issue explica esto? ¿Se van a poner a false en vez de borrarse? ¿Cómo sabes los que hay disponibles?

2021-11-09 13:15 UTC, JJ commented on src/Appointment.js
>  		this.customerName = customerName;
¿Cómo puede esto no tener la hora? Si el mismo cliente saca uno nuevo, ¿qué haces? ¿Dónde está el issue que justifica eso?

2021-11-09 14:44 UTC, jesusmarzor commented
He realizado los cambios pedidos.

No tenía sentido *una cita sin hora* porque por definición una cita tiene asociada una hora.

Ahora **cada día tiene un array de Appointment** y cada uno con su hora :smile: 

Listo para revisión @JJ

2021-11-09 15:40 UTC, JJ commented
Cambiar "hacer la tarea" por "solucionar el problema" no soluciona ningún problema ni explica cómo lo hace. Por favor, tratad de entender lo que se os pide en vez de hacer literalmente lo que se está pidiendo.

2021-11-09 16:03 UTC, JJ commented
¿Honestamente? Cerrar este PR y empezar de nuevo siguiendo buenas prácticas. Mirar la lista de comprobación, hacer los issues que correspondan a las HUs que vayas a desarrollar, añadir la documentación que se pide, etcétera.

2021-11-09 16:09 UTC, closed without merging