Objetivo 5
jesusmarzor/Peluqueria pull request #46
Opened 2021-11-29 15:44 UTC by jesusmarzor

En este objetivo:
- Se crea un contenedor para ejecutar los test #44 
- Se crea un Github Actions para mantener el contenedor actualizado #45 
- Se crean scripts en el package.json para construir y ejecutar el contenedor.
- Se actualiza la documentación.

2021-11-29 19:14 UTC, jesusmarzor commented
Me ha costado mucho darme cuenta que lo que estaba fallando era que tenía mal el nombre de la variable de *secrets* y he probado de todo para solucionar algo que era imposible al no tener correcta esa variable :sob: . Pero ya lo he solucionado.

He intentado mejorar las buenas prácticas de los commits :smile: 

Listo para revision @JJ

2021-11-30 11:24 UTC, JJ commented
Por favor, recuerda poner siempre [IV-21-22] en tus PRs para que pueda encontrarlos fácilmente entre los cientos de mensajes que recibo al día.

2021-11-30 11:31 UTC, JJ requested changes
El Dockerfile tiene errores, también la justificación.

2021-11-30 11:31 UTC, JJ commented on .gitignore
>  # should NOT be excluded as they contain compiler settings and other important
??? ¿Qué es este subdirectorio?

2021-11-30 11:31 UTC, JJ commented on Dockerfile
> +RUN npm ci
Esto no se ejecuta en el directorio que se monta. Mira en errores frecuentes.

2021-11-30 11:31 UTC, JJ commented on Dockerfile
> +RUN npm ci
De hecho, también en la lista de comprobación.

2021-11-30 11:31 UTC, JJ commented on Dockerfile
> +COPY package*.json ./
COPY se va a ejecutar como root no matter what. Si quieres que tenga permisos de usuario, usa `--chown`

2021-11-30 11:31 UTC, JJ commented on docs/Objetivo-5/DOCKER.md
> +Por otro lado, he escogido la versión **alpine** ya que es la imagen más pequeña que nos ofrece docker. A esta versión le instalaremos las dependencias de nuestra aplicación, así tendremos una imagen
alpine no es una versión, es una distro. En todo caso, esta justifciación está mal. También se ha explicado en clase como hacer una buena justificación.

2021-11-30 18:16 UTC, jesusmarzor commented
Listo para revisión @JJ

2021-12-01 08:15 UTC, JJ approved these changes
Por favor, corrige lo del directorio ese y listo.

2021-12-01 08:15 UTC, JJ commented on .gitignore
>  # should NOT be excluded as they contain compiler settings and other important
¿Por qué sigue aquí este subdirectorio? ¿Has hecho git add .?

2021-12-01 10:17 UTC, jesusmarzor commented
No sabía a que subdirectorio se refería pero por si acaso he eliminado todo el *.gitignore* que venía por defecto y he dejado solo lo que necesito.
Listo para revisión @JJ

2021-12-01 10:48 UTC, JJ commented
Ya estaba revisado y aprobado porque el objetivo estaba alcanzado, pero te agradezco que hagas los cambios pedidos. Ahora a por el siguiente.

2021-12-02 09:50 UTC, merged