[IV-21-22] Objetivo 6
jesusmarzor/Peluqueria pull request #48
Opened 2021-12-02 18:00 UTC by jesusmarzor

En este objetivo se eligen dos servicios de integración continua.

- [x]  ¿Se han configurado varios sistemas de integración continua?
- [x]  ¿Se ha configurado correctamente el *Checks API* en los sistemas en los que sea necesario para que aparezca correctamente en GitHub (y se pueda comprobar desde los tests)?
- [x]  ¿Uno de los sistemas configurados permite comprobar cuales son las versiones del lenguaje con las que funciona correctamente nuestra aplicación?
- [x]  ¿Se escogen de forma adecuada las versiones del lenguaje que se testean, tanto en el sistema de CI como en el contenedor Docker?

2021-12-02 20:02 UTC, jesusmarzor commented
Listo para revision @JJ

2021-12-05 20:17 UTC, JJ requested changes
Como en todas las decisiones técnicas, tienes que establecer criterios de elección de los sistemas de CI y también mostrar cuales hay, no decir los que ha elegido y copiar la publicidad de su página.
También tienes que justificar las versiones del lenguaje elegidas.

2021-12-05 20:17 UTC, JJ commented on docs/Objetivo-6/CI.md
> +Como segundo CI, he escogido [SemaphoreCI](https://semaphoreci.com/) porque gracias a los recursos de hardware dedicados puede procesar más rápido que los productos de la competencia y oferce ejecuci
Tío, no pongas la publicidad del sistema. Di lo que tiene, cómo se configura, todo eso.

2021-12-05 20:17 UTC, JJ commented on docs/Objetivo-6/CI.md
> +Desde la propia web, puedes observar como se van ejecutando los test y si quieres modificar el fichero *.yml*, puedes hacerlo desde ahí y hacer un push en la rama donde se encuentra el fichero o crea
Absolutamente en todos.

2021-12-09 09:47 UTC, jesusmarzor commented
Listo para revisión @JJ

2021-12-09 19:23 UTC, JJ approved these changes
Sigues sin justificar correctamente las elecciones, pero esto ya no va a mejorar. A por el siguiente.

2021-12-09 19:23 UTC, JJ commented on docs/Objetivo-6/CI.md
> +
Los criterios de aceptación y de búsqueda siempre tienen que ir antes.

2021-12-09 19:23 UTC, JJ commented on docs/Objetivo-6/CI.md
> +Como primer CI, he escogido [Travis-CI](https://www.travis-ci.com/about-us/) porque el entorno de integración continua esta compuesto de multiples runtimes. De este modo, podemos probar nuestro códig
Evita faltas de ortografía, por favor.

2021-12-20 09:50 UTC, merged