[IV-21-22] Objetivo 7
jesusmarzor/Peluqueria pull request #51
Opened 2021-12-20 18:59 UTC by jesusmarzor

2021-12-21 20:49 UTC, modejota commented on src/utils/Configuration.js
> +      this.logDir = (process.env.LOG_DIR || '/tmp/logs/peluqueria/');
No sabia que se podía asignar así, me lo apunto.

2021-12-21 20:51 UTC, modejota commented on test/App.test.js
> +    await new Promise(resolve => setTimeout(() => resolve(), 1000));
Esto es lo que te dije que no terminaba de entender porqué lo hacías, Jest en Typescript no requiere nada de esto.

2021-12-22 07:10 UTC, JJ requested changes
Un pequeño repaso a lo indicado y lo tienes.

2021-12-22 07:10 UTC, JJ commented on package.json
> +    "test": "jest --detectOpenHandles",
Esto tendrás que explicármelo. Ya lo he visto en un par de sitios y no sé muy bien qué hace ni cómo se aplica a tu caso en particular.

2021-12-22 07:10 UTC, JJ commented on src/App.js
> +			logger.info('No se ha podido crear el servicio ' + name);
Si hay un error no puedes usar `info`

2021-12-22 07:10 UTC, JJ commented on src/utils/Configuration.js
> +    this.logDir = null;
Indentación. Usa un IDE que lo haga por ti.

2021-12-22 07:10 UTC, JJ commented on src/utils/Configuration.js
> +    if(this.logDir === null){
No estás usando dotenv para cargar la configuración. Llamas a `config()` arriba pero no parece que lo asignes a nada.

2021-12-22 07:10 UTC, JJ commented on src/utils/logger.js
> +const config = new Configuration();
No es buena práctica usar variables globales. Debes inyectarlo en cada objeto, porque la configuración puede cambiar en tiempo de ejecución (por ejemplo, en los tests)

2021-12-22 07:10 UTC, JJ commented on test/App.test.js
> +    await new Promise(resolve => setTimeout(() => resolve(), 1000));
Lo que esto hace es esperar. El problema es que si estás usando llamadas asíncronas, puede salir antes de tiempo, pero esta no es la solución. Lo que tienes que hacer son tests asíncronos.

2021-12-22 15:24 UTC, jesusmarzor commented on src/utils/Configuration.js
> +      this.logDir = (process.env.LOG_DIR || '/tmp/logs/peluqueria/');
Yo en lo personal, hubiera usado directamente el Logical nullish assignment(??=) pero en las versiones 12 y 14 de node me daba error y he acabado usando un if. Esto lo cambie en este commit 91719b1

2021-12-22 15:30 UTC, jesusmarzor commented on test/App.test.js
> +    await new Promise(resolve => setTimeout(() => resolve(), 1000));
Probé a usar test asíncronos pero me sigue dando error en los test. Creo que es porque se queda esperando a que llegue algo de la llamada a client de Etcd3. ¿Cómo puedo evitar el error de client?

2021-12-22 15:35 UTC, jesusmarzor commented on package.json
> +    "test": "jest --detectOpenHandles",
En mi caso, lo he puesto porque al usar client de Etcd3 me lo advertía jest.
```
Jest did not exit one second after the test run has completed.

This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.
```

2021-12-22 15:50 UTC, jesusmarzor commented
Listo para revisión @JJ

2021-12-22 17:03 UTC, JJ commented on src/utils/logger.js
> +const config = new Configuration();
No has hecho ningún cambio aquí.

2021-12-22 17:09 UTC, JJ requested changes
Sigue estando el problema de las cosas asíncronas. Y también algún comentario sobre el que no has hecho nada.

2021-12-22 17:09 UTC, JJ commented on package.json
> +    "test": "jest --detectOpenHandles",
Lo que tienes que hacer es hacer los tests correctamente, haciendo tests asíncronos de llamadas asíncronas.

2021-12-22 17:09 UTC, JJ commented on test/App.test.js
>      app = new App();
¿Estoy viendo una variable sin declarar? Seguramente esta llamada tenga que ser asíncrona, sobre todo si el arranque del app es asíncrono. Tienes que aprender a trabajar con este tipo de llamadas asíncronas, y evitar la ñapa de abajo.

2021-12-22 17:09 UTC, JJ commented on src/utils/Configuration.js
> +const client = new Etcd3();
Las variables globales NUNCA son una buena costumbre. ¿Vas a inicializarla antes de abrir una instancia? ¿Todas las instancias van a compartir la misma conexión?

2021-12-22 17:09 UTC, JJ commented on src/utils/Configuration.js
> +	    (async () => this.logDir = await client.get('LOG_DIR').string().catch( err => console.log('Log_Dir', err.message)))();
Esta ñapa es la que hace que luego tengas que meter el bucle y hacer esas cosas asíncronas. Por favor, aprende como gestionar esto correctamente.

2022-01-19 17:25 UTC, JJ approved these changes
No hay prácticamente ninguna solución que no haya tomado alguien antes, y algunas decisiones son cuestionables, pero a estas alturas no da tiempo de corregirlo, así que aprobado.

2022-01-19 17:25 UTC, JJ commented on docs/Objetivo-6/CI.md
> +Como criterio para la elección de CI, quiero que se pueda integrar de manera fácil con github y que ejecute los test muy rápido.
Los criterios que debes poner deben ser más estrictos. Estos criterios lo cumple cualquier sistema de CI.

2022-01-19 17:25 UTC, JJ commented on package.json
> +    "test": "jest --detectOpenHandles",
Esto no lo has hecho.

2022-01-19 17:25 UTC, JJ commented on src/App.js
> +		if(service){
Estás haciendo push antes de saber si se ha creado.

2022-01-19 17:25 UTC, JJ commented on src/utils/Configuration.js
> +require('dotenv').config({ path: './configuration.env'});
Este camino debe ser siempre el que haya por omisión.

2022-01-25 16:36 UTC, merged